@plr = player()


@hero = associative_array(
            'name': '§9D§1.v§9a',
            'class': 'dva',
            'sig': 'S3MUOg05pUOxrfjRGD89yRBGra6sW7WpjJ2nK6FQYtv5dYxynnsY84r6PpagOkQHNEk8JCVF65EkwuJMV+NpN9/cDCiGrMNsTVAjWzcIceKIljpLX0iVS/37/SLZMRiOp0KEKlfmt+w7foR64t8VtZsNXzvWRC9AkbcRWVJAhfe6cpuzCoz4mo4XO8mKhP/hJ6SAMlWQtkYcOvQ34Vna/k06HxgIzVPvQNSjW/OhGJhxUQi7+x3rqzLoL8ifVMpPZ+Gxvd6ylQAvQ2Cf8kZryvrCicfcaF09I6Y4KgG8oBcX9nVqz7QdPnmXFqZqg7+vtdOJBKwut+lxSJ7xFRCqGiCygfbUjwESky8aPICcox+DcVW8ERC15vJTnYqiHWBzkAlLl3wIkoBEoF/hcywIAO6oPvOIUb4wYg8tZGZfysHxrICAzyDUo34bfve0yE/k6/DbfwnK4Cg9T/tf+MI1IzUEetnme9vCdIiDiAm+8BP18rqY41v9AWYH0yYxcoxehbzmOVqLLDpbHjgXM1GbpS8Slt1I9ygXPUKz3JbyKoE0b6mGM7uu6VOur1EeM7xSQsem360OinJTMccJiBKyXPaH1dOh2CXNquM9++E2l0HjVeeHeoO9ob/EaFSsiZutTYFL7KnvmWv/DN4MLHcj6cV3IzBoDCW6w7oQREuw1SE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTQ1NDc1NDk5OTMsInByb2ZpbGVJZCI6IjcyOTFkNzZhNzQyMjQ2NWZhYmM4ODRiMDgwNzM4ZDkyIiwicHJvZmlsZU5hbWUiOiJCYXRQYW5kbyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzZjYzVkYWJlYWRhMzlkN2E3MDExZDdjN2ZkODU3ZTdmNmEyZWJjMTJkOGU3NjYyNGIxZDc3MjA0MTMxZTIifX19',
            'trail': '',
            'op': 'false',
            'speech': "Let's do this!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-1",
                "/",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." Light Gun",              
            )
        )
